name: CI
on: [push, pull_request]
jobs:
  python-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ ubuntu-20.04 ]
        python-version: [ '3.8' ]
        toxenv: [ django22, django30, django31, django32 ]
    steps:
      - uses: actions/checkout@v2

      - name: Python setup
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: tox install
        run: pip install tox

      - name: Run Tests
        run: tox

      - name: Upload coverage to CodeCov
        uses: codecov/codecov-action@v1
        with:
          file: ./coverage.xml
          fail_ci_if_error: true
